version: '3.3'

services: 
  haproxy:
     image: haproxy:latest
     container_name: haproxy
     ports:
      - "85:85"
     volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./haproxy_logs:/var/log/haproxy
     networks:
      - webnet
  prometheus:
     image: prom/prometheus:latest
     container_name: prometheus
     ports:
      - "9090:9090"
     volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
     networks:
      - webnet
  grafana:
     image: grafana/grafana:latest
     container_name: grafana
     ports:
      - "3000:3000"
     networks:
      - webnet
     depends_on:
      - prometheus
networks:
     webnet:
         driver: bridge 
